version: "3.9"

services:

  backend:
    container_name: fastapi-backend

    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      DB_USER: fastapi
      DB_PASSWORD: "Password@123"
      DB_HOST: "35.170.55.91"
      DB_PORT: "3306"
      DB_NAME: companydb

    restart: unless-stopped

    networks:
      - fastapi-network

  frontend:
    container_name: fastapi-frontend

    build:
      context: ./frontend
      dockerfile: Dockerfile

    depends_on:
      - backend

    ports:
      - "80:80"

    restart: unless-stopped

    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
